version: 2.1

workflows:
  workflow:
    jobs:
      - job:
          working_directory: "/mnt/ramdisk"

executors:
  default:
    machine: true
    working_directory: "/mnt/ramdisk"

jobs:
  job:
    parameters:
      working_directory:
        type: "string"
    executor: default
    steps:
      - run: sudo mkdir /mnt/ramdisk
