version: 2.1

executors:
  docker-executor: # for use with CCC. need a different image than the others to prevent errors
    docker:
       - image: alpine
    working_directory: /mnt/ramdisk
    resource_class: medium

jobs:
  test:
    executor: docker-executor
    docker: 
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.11
      - run: docker info

workflows:
  main:
    jobs:
      - test