version: 2.1

workflows:
  workflow:
    jobs:
      - job

jobs:
  job:
    docker:
    - image: cimg/base:stable
    steps:
      - run: echo foo > /tmp/file.txt
      - store_artifacts:
          path: /tmp/file.txt
