version: 2.1

workflows:
  workflow:
    jobs:
      - job

executors:
  default:
    machine: true
    working_directory: "/mnt/ramdisk"

jobs:
  job:
    executor: default
    steps:
      - run:
         command: 'sudo mkdir /mnt/ramdisk && sudo chown circleci: /mnt/ramdisk && sudo mount -t tmpfs tmpfs /mnt/ramdisk -o rw,nodev,suid,exec,size=10G'
         working_directory: /home/circleci
      - run: ls -lR /mnt

